### ISSUE TITLE
バグを発見しました~

### ISSUE THREAD

**Issue by 981377660LMT** [maspypy/library#2]
https://github.com/maspypy/library/blob/a23f19f4de7132b5240a41e40e98a909c1bf04f9/knapsack/subset_sum_count.hpp#L13

ここは
``` cpp
vc<T> dp1 = dp;
```
と思います.

**Comment by 981377660LMT** [comment]
https://github.com/maspypy/library/blob/81c6c5dc27dc5442f007b01cee34f0507b7aa3f0/ds/intervals.hpp#L30
https://github.com/maspypy/library/blob/81c6c5dc27dc5442f007b01cee34f0507b7aa3f0/ds/intervals.hpp#L127

ここは x じゃなくて、
```
if (t != none_val && ERASE) { 
```
と思います。

**Comment by 981377660LMT** [comment]
とても勉強になりました!

**Comment by maspypy** [comment]
修正しました、ありがとうございます！
