### ISSUE TITLE
find_cycle_undirected について

### ISSUE THREAD

**Issue by 981377660LMT** [maspypy/library#3]
https://github.com/maspypy/library/blob/59f42d4d81ca40eadcec713cf0de214bc5bdd054/graph/find_cycle.hpp#L42-L45

検証してみたら、「極小なものを返す」はできません。( 実際、O(n)では厳しいと思います )

```
n=7 m=7 edges= [[1,3],[3,5],[5,1],[0,2],[2,4],[4,6],[6,0]] 

7 7
7 7
1 3
3 5
5 1
0 2 
2 4
4 6
6 0
=>
出力：0、6、4、2　からなるサイクル

極小なものじゃないです。正解は 1、3、5 です。
```
もし何か問題があれば，教えて頂けると助かります。

**Comment by maspypy** [comment]
「極小」 (local) minimal
「最小」 minimum, smallest

の言葉の違いがあって、このコードでの極小サイクル $C$ とは、次を満たすものを指しています。

・$C$ はサイクル
・サイクルであって、頂点集合が $C$ の真部分集合であるものは存在しない。

同値な言い換えとして、「サイクルであって弦が存在しないもの」と言ってもよいです。
これでどうでしょうか？

次の解答で使用しています。
https://codeforces.com/contest/1364/submission/195478431

**Comment by 981377660LMT** [comment]
> 「極小」 (local) minimal 「最小」 minimum, smallest
> 
> の言葉の違いがあって、このコードでの極小サイクル C とは、次を満たすものを指しています。
> 
> ・$C$ はサイクル ・サイクルであって、頂点集合が C の真部分集合であるものは存在しない。
> 
> 同値な言い換えとして、「サイクルであって弦が存在しないもの」と言ってもよいです。 これでどうでしょうか？
> 
> 次の解答で使用しています。 https://codeforces.com/contest/1364/submission/195478431

わかりました。ありがとうございます!
