### ISSUE TITLE
FASTIO

### ISSUE THREAD

**Issue by ZrjaK** [maspypy/library#7]
These codes are not suitable for other implementations of FASTIO.

https://github.com/maspypy/library/blob/6c4cd5a3d8c3219692f1b7cc98a5cac630c7fb24/mod/modint.hpp#L81C14-L81C14
```cpp
#ifdef FASTIO
template <int mod>
void rd(modint<mod> &x) {
  fastio::rd(x.val);
  assert(0 <= x.val && x.val < mod);
}
template <int mod>
void wt(modint<mod> x) {
  fastio::wt(x.val);
}
#endif
```

There are many places that have this problem.This is an example.

To the people who implement `read/print` with `cin/cout`, I think this would be better.

```cpp
#ifdef FASTIO
template <int mod>
void read(modint<mod> &x) {
  read(x.val);
  assert(0 <= x.val && x.val < mod);
}
template <int mod>
void print(modint<mod> x) {
  print(x.val);
}
#endif
```

**Comment by maspypy** [comment]
I think this change is not needed. 

- This library is simply my own library. Basically, The priority of for others is low.
- If others want to use this, they can use if he don't define FASTIO. 

But I'm not strongly disagree with your proposal. 
If my IO works with your proposal, I can change. (Now, my IO is broken if I just change it as proposed.)

I want to design my `print` function as follows: 
- `print(x)` = `cout << x << "\n"'
- `print(x, y)` = `cout << x << " " << y << "\n"'
- If A is vector, `print(A)` = `print(A[0], A[1], ..., A[n-1])`

To achieve this, I used different name from `print`.

**Comment by ZrjaK** [comment]
You are right.I ignore the overload of `print`.
Thank you for the reply,I will close the issue.
